# Generated by Django 5.1.6 on 2026-03-31 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('expense_type', models.CharField(choices=[('salary', 'Salary'), ('bonus', 'Bonus'), ('medical', 'Medical'), ('travel', 'Travel'), ('equipment', 'Equipment'), ('training', 'Training'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Expense Category',
                'verbose_name_plural': 'Expense Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyExpensePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('month', models.DateField(help_text='Plan for month')),
                ('planned_salary', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('planned_bonus', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('planned_medical', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('planned_travel', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('planned_other', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_planned', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('planned', 'Planned'), ('approved', 'Approved'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monthly Expense Plan',
                'verbose_name_plural': 'Monthly Expense Plans',
                'ordering': ['-month'],
                'unique_together': {('month',)},
            },
        ),
    ]
