# Generated by Django 5.1.6 on 2026-04-01 06:31

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_expensecategory_monthlyexpenseplan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('expense_month', models.DateField(help_text='Month this expense belongs to (first day of month)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('expense_date', models.DateField(help_text='Actual date of expense')),
                ('receipt', models.FileField(blank=True, null=True, upload_to='expense_receipts/')),
                ('transaction_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Actual Expense',
                'verbose_name_plural': 'Actual Expenses',
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='salaryrecord',
            options={'ordering': ['-month', 'employee'], 'verbose_name': 'Salary Record', 'verbose_name_plural': 'Salary Records'},
        ),
        migrations.AddField(
            model_name='employee',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='monthlyexpenseplan',
            name='planned_equipment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='monthlyexpenseplan',
            name='planned_training',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='salary_payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_record', to='hr.salarypayment'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(decimal_places=2, help_text='Monthly base salary', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='monthlyexpenseplan',
            name='month',
            field=models.DateField(help_text='First day of the plan month (e.g., 2024-01-01 for January 2024)'),
        ),
        migrations.AlterField(
            model_name='monthlyexpenseplan',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('planned', 'Planned'), ('approved', 'Approved'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='salarypayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='salarypayment',
            name='month',
            field=models.DateField(help_text='First day of the salary month (e.g., 2024-01-01 for January 2024)'),
        ),
        migrations.AlterField(
            model_name='salaryrecord',
            name='month',
            field=models.DateField(help_text='First day of the salary month (e.g., 2024-01-01 for January 2024)'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['is_active'], name='hr_employee_is_acti_8381ca_idx'),
        ),
        migrations.AddIndex(
            model_name='salarypayment',
            index=models.Index(fields=['status'], name='hr_salarypa_status_fe22ec_idx'),
        ),
        migrations.AddIndex(
            model_name='salaryrecord',
            index=models.Index(fields=['month'], name='hr_salaryre_month_3caa3a_idx'),
        ),
        migrations.AddIndex(
            model_name='salaryrecord',
            index=models.Index(fields=['is_paid'], name='hr_salaryre_is_paid_00c1c8_idx'),
        ),
        migrations.AddConstraint(
            model_name='salarypayment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'processing', 'completed'])), fields=('employee', 'month'), name='unique_active_payment_per_month'),
        ),
        migrations.AddField(
            model_name='actualexpense',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='hr.expensecategory'),
        ),
        migrations.AddField(
            model_name='actualexpense',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_recorded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actualexpense',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='hr.employee'),
        ),
        migrations.AddIndex(
            model_name='actualexpense',
            index=models.Index(fields=['expense_id'], name='hr_actualex_expense_cac8b8_idx'),
        ),
        migrations.AddIndex(
            model_name='actualexpense',
            index=models.Index(fields=['expense_month'], name='hr_actualex_expense_822adf_idx'),
        ),
        migrations.AddIndex(
            model_name='actualexpense',
            index=models.Index(fields=['status'], name='hr_actualex_status_61bc13_idx'),
        ),
        migrations.AddIndex(
            model_name='actualexpense',
            index=models.Index(fields=['category'], name='hr_actualex_categor_912e12_idx'),
        ),
    ]
