# Generated by Django 6.0.3 on 2026-04-03 09:43

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0004_remove_project_hourly_rate_and_more'),
        ('hr', '0003_actualexpense_alter_salaryrecord_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('benefit_type', models.CharField(choices=[('travel', 'Travel Allowance'), ('medical', 'Medical/Health Insurance'), ('training', 'Training/Certification'), ('phone', 'Phone/Internet Reimbursement'), ('equipment', 'Equipment Allowance'), ('other', 'Other Benefit')], max_length=20)),
                ('annual_limit', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('used_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave blank for ongoing', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='hr.employee')),
            ],
            options={
                'verbose_name': 'Employee Benefit',
                'verbose_name_plural': 'Employee Benefits',
                'ordering': ['-start_date', 'employee'],
                'indexes': [models.Index(fields=['employee', 'benefit_type', 'is_active'], name='hr_employee_employe_040233_idx'), models.Index(fields=['benefit_type', 'is_active'], name='hr_employee_benefit_8b8112_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('salary', 'Salary Payment'), ('bonus', 'Bonus'), ('benefit', 'Benefit Used'), ('expense', 'Expense Reimbursement'), ('adjustment', 'Manual Adjustment')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount owed to employee', max_digits=15)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount paid to employee', max_digits=15)),
                ('running_balance', models.DecimalField(decimal_places=2, help_text='Pending balance after this entry', max_digits=15)),
                ('transaction_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='hr.employee')),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='hr.actualexpense')),
                ('salary_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='hr.salarypayment')),
            ],
            options={
                'verbose_name': 'Employee Ledger Entry',
                'verbose_name_plural': 'Employee Ledger Entries',
                'ordering': ['transaction_date', 'created_at'],
                'indexes': [models.Index(fields=['employee', 'transaction_date'], name='hr_employee_employe_680fe0_idx'), models.Index(fields=['employee', 'transaction_type'], name='hr_employee_employe_690be3_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('role_on_project', models.CharField(help_text='Role on this project (e.g., Lead Developer)', max_length=100)),
                ('hours_per_week', models.PositiveIntegerField(default=40, help_text='Hours allocated per week')),
                ('is_primary', models.BooleanField(default=False, help_text="Is this the employee's primary project?")),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave blank if ongoing', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_assignments', to='hr.employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_assignments', to='client_management.project')),
            ],
            options={
                'verbose_name': 'Project Assignment',
                'verbose_name_plural': 'Project Assignments',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['employee', 'is_active'], name='hr_projecta_employe_454718_idx'), models.Index(fields=['project', 'is_active'], name='hr_projecta_project_ad733f_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('employee', 'project'), name='unique_active_assignment_per_project')],
            },
        ),
        migrations.CreateModel(
            name='ProjectManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_projects_hr', to='hr.employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_managers', to='client_management.project')),
            ],
            options={
                'verbose_name': 'Project Manager',
                'verbose_name_plural': 'Project Managers',
                'ordering': ['assigned_date'],
                'constraints': [models.UniqueConstraint(fields=('project', 'employee'), name='unique_project_manager')],
            },
        ),
    ]
