# Generated by Django 5.2.12 on 2026-03-24 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Service Category Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('icon', models.CharField(blank=True, help_text='FontAwesome icon class', max_length=50, null=True, verbose_name='Icon')),
                ('color_code', models.CharField(blank=True, help_text='Hex color code', max_length=7, null=True, verbose_name='Color Code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_service_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service Category',
                'verbose_name_plural': 'Service Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Service Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('base_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Base Price')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_services', to=settings.AUTH_USER_MODEL)),
                ('service_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.servicecategory', verbose_name='Service Category')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['service_category', 'name'],
                'unique_together': {('service_category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SubService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Sub-Service Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('code', models.CharField(help_text='Unique code for this sub-service (e.g., WEB-ECOMM, GRAPH-BRAND)', max_length=50, unique=True, verbose_name='Service Code')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Standard Price')),
                ('estimated_duration_days', models.PositiveIntegerField(default=7, verbose_name='Estimated Duration (Days)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('requires_approval', models.BooleanField(default=False, verbose_name='Requires Approval')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sub_services', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_services', to='services.service', verbose_name='Main Service')),
            ],
            options={
                'verbose_name': 'Sub-Service',
                'verbose_name_plural': 'Sub-Services',
                'ordering': ['service__service_category', 'service', 'name'],
                'unique_together': {('service', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ServicePricingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Old Price')),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='New Price')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Changed At')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Reason for Change')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_changes', to=settings.AUTH_USER_MODEL, verbose_name='Changed By')),
                ('sub_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_history', to='services.subservice', verbose_name='Sub-Service')),
            ],
            options={
                'verbose_name': 'Service Pricing History',
                'verbose_name_plural': 'Service Pricing Histories',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('custom_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Custom Price')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_services', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_services', to='core.client', verbose_name='Client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_client_services', to=settings.AUTH_USER_MODEL)),
                ('sub_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_services', to='services.subservice', verbose_name='Sub-Service')),
            ],
            options={
                'verbose_name': 'Client Service',
                'verbose_name_plural': 'Client Services',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategoryAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(verbose_name='Month')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Total Revenue')),
                ('total_clients', models.PositiveIntegerField(default=0, verbose_name='Total Clients')),
                ('total_projects', models.PositiveIntegerField(default=0, verbose_name='Total Projects')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='services.servicecategory', verbose_name='Service Category')),
            ],
            options={
                'verbose_name': 'Service Category Analytics',
                'verbose_name_plural': 'Service Category Analytics',
                'ordering': ['service_category', '-month'],
                'unique_together': {('service_category', 'month')},
            },
        ),
    ]
