# Generated by Django 5.2.12 on 2026-03-13 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('basic_percentage', models.DecimalField(decimal_places=2, default=50, help_text='Percentage of basic salary', max_digits=5)),
                ('hra_percentage', models.DecimalField(decimal_places=2, default=40, help_text='House Rent Allowance percentage', max_digits=5)),
                ('conveyance_allowance', models.DecimalField(decimal_places=2, default=0, help_text='Fixed conveyance allowance', max_digits=8)),
                ('medical_allowance', models.DecimalField(decimal_places=2, default=0, help_text='Fixed medical allowance', max_digits=8)),
                ('special_allowance', models.DecimalField(decimal_places=2, default=0, help_text='Special allowance', max_digits=8)),
                ('pf_percentage', models.DecimalField(decimal_places=2, default=12, help_text='Provident Fund percentage', max_digits=5)),
                ('esi_percentage', models.DecimalField(decimal_places=2, default=0.75, help_text='ESI percentage', max_digits=5)),
                ('professional_tax', models.DecimalField(decimal_places=2, default=0, help_text='Professional tax amount', max_digits=8)),
                ('tds_percentage', models.DecimalField(decimal_places=2, default=0, help_text='TDS percentage', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Salary Structure',
                'verbose_name_plural': 'Salary Structures',
            },
        ),
        migrations.CreateModel(
            name='StaffInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField()),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('hours_worked', models.DecimalField(decimal_places=2, max_digits=8)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='staff.staff')),
            ],
            options={
                'verbose_name': 'Staff Invoice',
                'verbose_name_plural': 'Staff Invoices',
                'ordering': ['-invoice_date'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='salary.staffinvoice')),
            ],
            options={
                'verbose_name': 'Invoice Line Item',
                'verbose_name_plural': 'Invoice Line Items',
            },
        ),
        migrations.CreateModel(
            name='SalarySlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='Month of salary (use first day of month)')),
                ('basic', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('conveyance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medical', models.DecimalField(decimal_places=2, max_digits=10)),
                ('special', models.DecimalField(decimal_places=2, max_digits=10)),
                ('overtime', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pf', models.DecimalField(decimal_places=2, max_digits=10)),
                ('esi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('professional_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tds', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loan_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('advance_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gross_earnings', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_deductions', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('working_days', models.DecimalField(decimal_places=2, default=30, max_digits=5)),
                ('days_present', models.DecimalField(decimal_places=2, max_digits=5)),
                ('days_absent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('leave_taken', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_slips', to='staff.staff')),
                ('salary_structure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='salary.salarystructure')),
            ],
            options={
                'verbose_name': 'Salary Slip',
                'verbose_name_plural': 'Salary Slips',
                'ordering': ['-month', 'staff'],
                'unique_together': {('staff', 'month')},
            },
        ),
        migrations.CreateModel(
            name='SalaryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('custom_base_salary', models.DecimalField(blank=True, decimal_places=2, help_text='Override base salary if different from staff/role', max_digits=10, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_assignments', to='staff.staff')),
                ('salary_structure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='salary.salarystructure')),
            ],
            options={
                'verbose_name': 'Salary Assignment',
                'verbose_name_plural': 'Salary Assignments',
                'ordering': ['-effective_from'],
                'unique_together': {('staff', 'effective_from')},
            },
        ),
    ]
