# Generated by Django 5.1.6 on 2026-04-01 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0001_initial'),
        ('services', '0002_alter_clientservice_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='alternative_phone',
        ),
        migrations.RemoveField(
            model_name='client',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='client',
            name='city',
        ),
        migrations.RemoveField(
            model_name='client',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='country',
        ),
        migrations.RemoveField(
            model_name='client',
            name='credit_limit',
        ),
        migrations.RemoveField(
            model_name='client',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='client',
            name='payment_terms',
        ),
        migrations.RemoveField(
            model_name='client',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='client',
            name='primary_contact_designation',
        ),
        migrations.RemoveField(
            model_name='client',
            name='primary_contact_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='secondary_contact_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='secondary_contact_phone',
        ),
        migrations.RemoveField(
            model_name='client',
            name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='client',
            name='source',
        ),
        migrations.RemoveField(
            model_name='client',
            name='state',
        ),
        migrations.RemoveField(
            model_name='client',
            name='website',
        ),
        migrations.AddField(
            model_name='client',
            name='subscribed_services',
            field=models.ManyToManyField(blank=True, related_name='subscribed_clients', to='services.subservice', verbose_name='Sub-Services'),
        ),
    ]
