# Generated by Django 5.1.6 on 2026-04-01 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0002_remove_client_alternative_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='assigned_to',
        ),
        migrations.AlterField(
            model_name='clientcommunication',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications', to='client_management.client'),
        ),
        migrations.AlterField(
            model_name='clientdocument',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='client_management.client'),
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='client_management.client'),
        ),
    ]
