# Generated by Django 5.1.6 on 2026-04-01 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0003_remove_client_assigned_to_and_more'),
        ('hr', '0003_actualexpense_alter_salaryrecord_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='hourly_rate',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_type',
        ),
        migrations.RemoveField(
            model_name='project',
            name='total_cost',
        ),
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Project Cost'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to='hr.employee'),
        ),
        migrations.AlterField(
            model_name='project',
            name='team_members',
            field=models.ManyToManyField(blank=True, related_name='assigned_projects', to='hr.employee'),
        ),
    ]
