# Generated by Django 5.2.12 on 2026-03-13 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignments', '0001_initial'),
        ('projects', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='projects.project'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='staff.role'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='staff.staff'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['staff', 'is_active'], name='assignments_staff_i_c7cfa0_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['project', 'is_active'], name='assignments_project_c92a9e_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['status'], name='assignments_status_63bdfc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together={('staff', 'project', 'is_active')},
        ),
    ]
