# Generated by Django 5.2.12 on 2026-03-13 12:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('base_salary', models.DecimalField(blank=True, decimal_places=2, help_text='Base salary for this role', max_digits=10, null=True)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Hourly rate for this role', max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('intern', 'Intern')], max_length=20)),
                ('payment_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('bi_weekly', 'Bi-Weekly'), ('weekly', 'Weekly'), ('hourly', 'Hourly')], default='monthly', max_length=20)),
                ('join_date', models.DateField(default=django.utils.timezone.now)),
                ('exit_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('base_salary', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly/Annual base salary', max_digits=10, null=True)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Hourly rate (for hourly employees)', max_digits=8, null=True)),
                ('overtime_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Overtime hourly rate (1.5x, 2x, etc.)', max_digits=8, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('ifsc_code', models.CharField(blank=True, max_length=20)),
                ('pan_number', models.CharField(blank=True, max_length=20)),
                ('tax_id', models.CharField(blank=True, help_text='Tax ID / Social Security Number', max_length=50)),
                ('tax_exemption', models.DecimalField(decimal_places=2, default=0, help_text='Tax exemption amount', max_digits=10)),
                ('annual_leave_balance', models.DecimalField(decimal_places=2, default=0, help_text='Annual leave days remaining', max_digits=5)),
                ('sick_leave_balance', models.DecimalField(decimal_places=2, default=0, help_text='Sick leave days remaining', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_staff', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='staff.role')),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
                'indexes': [models.Index(fields=['email'], name='staff_staff_email_87de38_idx'), models.Index(fields=['is_active', 'role'], name='staff_staff_is_acti_2d497e_idx')],
            },
        ),
    ]
