# Generated by Django 5.2.12 on 2026-03-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='expense',
            name='financial_e_expense_eca631_idx',
        ),
        migrations.RemoveIndex(
            model_name='expense',
            name='financial_e_categor_09e4d2_idx',
        ),
        migrations.RemoveIndex(
            model_name='expense',
            name='financial_e_status_85d4b7_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='financial_i_invoice_1438fe_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='financial_i_invoice_4a5a41_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='financial_i_status_c36524_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='financial_i_due_dat_48a32a_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='financial_p_payment_499d99_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='financial_p_transac_0e234e_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='financial_p_status_71a042_idx',
        ),
        migrations.AlterField(
            model_name='expense',
            name='is_billable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_terms',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('partial', 'Partially Paid'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
