# Generated by Django 5.2.12 on 2026-03-25 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0001_initial'),
        ('financial', '0002_remove_expense_financial_e_expense_eca631_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('date', models.DateField(unique=True)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_clients', models.IntegerField(default=0)),
                ('total_projects', models.IntegerField(default=0)),
                ('active_projects', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Revenue',
                'verbose_name_plural': 'Company Revenues',
                'ordering': ['-date'],
            },
        ),
        migrations.RemoveField(
            model_name='expense',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='client',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='project',
        ),
        migrations.DeleteModel(
            name='FinancialSummary',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='project',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='sub_service',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='client',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='project',
        ),
        migrations.RemoveField(
            model_name='revenue',
            name='payment',
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-invoice_date'], 'verbose_name': 'Invoice', 'verbose_name_plural': 'Invoices'},
        ),
        migrations.RemoveField(
            model_name='clientbalance',
            name='closing_balance',
        ),
        migrations.RemoveField(
            model_name='clientbalance',
            name='credit_limit',
        ),
        migrations.RemoveField(
            model_name='clientbalance',
            name='total_paid',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='balance_due',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_type',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='late_fee_percentage',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='paid_amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='payment_terms',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='sent_at',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='status',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='tax_amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='terms_and_conditions',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='revenue',
            name='revenue_type',
        ),
        migrations.AddField(
            model_name='clientbalance',
            name='pending_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount client still owes', max_digits=15),
        ),
        migrations.AddField(
            model_name='clientbalance',
            name='total_projects_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total cost of all projects', max_digits=15),
        ),
        migrations.AddField(
            model_name='invoice',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Auto-populated from project cost', max_digits=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientbalance',
            name='total_invoiced',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount paid by client', max_digits=15),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='client_management.project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='revenue',
            name='invoice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='revenues', to='financial.invoice'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='revenue',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='revenues', to='client_management.project'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.DeleteModel(
            name='InvoiceItem',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
