# Generated by Django 5.1.6 on 2026-03-31 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0004_invoice_amount_paid_invoice_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyrevenue',
            name='net_profit',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Revenue - Expenses', max_digits=15),
        ),
        migrations.AddField(
            model_name='companyrevenue',
            name='total_employees',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companyrevenue',
            name='total_expenses',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total expenses (salary, etc)', max_digits=15),
        ),
    ]
