# Generated by Django 5.1.6 on 2026-04-01 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0001_initial'),
        ('financial', '0006_alter_invoice_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='client_management.project'),
        ),
    ]
