# Generated by Django 5.1.6 on 2026-04-02 08:12

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


def cleanup_orphaned_records(apps, schema_editor):
    Revenue = apps.get_model('financial', 'Revenue')
    Payment = apps.get_model('financial', 'Payment')
    Project = apps.get_model('client_management', 'Project')

    valid_project_ids = set(Project.objects.values_list('id', flat=True))

    Revenue.objects.exclude(project_id__in=valid_project_ids).update(project_id=None)
    Payment.objects.exclude(project_id__in=valid_project_ids).update(project_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0004_remove_project_hourly_rate_and_more'),
        ('financial', '0008_alter_invoice_client_alter_payment_client_and_more'),
    ]

    operations = [
        migrations.RunPython(cleanup_orphaned_records, migrations.RunPython.noop),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='clientbalance',
                    name='total_invoiced',
                ),
            ],
            database_operations=[],
        ),
        migrations.AddField(
            model_name='clientbalance',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientbalance',
            name='pending_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='clientbalance',
            name='total_projects_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='companyrevenue',
            name='net_profit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='companyrevenue',
            name='total_expenses',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Total invoice amount', max_digits=15),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='payment',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='client_management.project'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenues', to='financial.invoice'),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenues', to='client_management.project'),
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='financial.invoice')),
            ],
            options={
                'verbose_name': 'Invoice Item',
                'verbose_name_plural': 'Invoice Items',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ClientLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('invoice', 'Invoice Created'), ('payment', 'Payment Received'), ('credit_note', 'Credit Note'), ('adjustment', 'Manual Adjustment')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount owed (invoice)', max_digits=15)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount paid (payment)', max_digits=15)),
                ('running_balance', models.DecimalField(decimal_places=2, help_text='Pending balance after this entry', max_digits=15)),
                ('transaction_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='client_management.client')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='financial.invoice')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='financial.payment')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='client_management.project')),
            ],
            options={
                'verbose_name': 'Client Ledger Entry',
                'verbose_name_plural': 'Client Ledger Entries',
                'ordering': ['transaction_date', 'created_at'],
                'indexes': [models.Index(fields=['client', 'transaction_date'], name='financial_c_client__00c80a_idx'), models.Index(fields=['client', 'transaction_type'], name='financial_c_client__1850bf_idx')],
            },
        ),
    ]
