# Generated by Django 6.0.3 on 2026-04-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0009_remove_clientbalance_total_invoiced_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('online', 'Online Payment'), ('card', 'Credit/Debit Card'), ('other', 'Other')], default='bank_transfer', max_length=20),
        ),
    ]
