# Generated by Django 6.0.3 on 2026-04-03 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0010_invoice_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_option',
            field=models.CharField(choices=[('full', 'Full Payment'), ('partial', 'Partial Payment')], default='full', help_text='Payment type: full or partial', max_length=20),
        ),
    ]
